### ISSUE TITLE
Pulse option on non-PWM (like the "Flipper Logic" option)

### ISSUE THREAD

**Issue by gate001** [mjrgh/PinscapeConfigTool#10]
I made a DIY chime but my concept is not the best, if the solenoid stay to much time active, the piston in contact with the bar of the chime stop the vibration of the bar so I do not have a nice "Diinngg". On the VPX tables, the time that the solenoids remains active is too long.
I was wondering if it's possible to have a "Flipper Logic" style option but for non-PWM outputs. A "Pulse" option where you can put the maximum time that the output stay active (in millisecond).

**Comment by mjrgh** [comment]
I've heard that the same thing applies to real chime units as well, so this seems like a useful addition.

I just took a look at the firmware code, and it looks like it'll be perfectly happy to apply flipper logic to digital outs.  It obviously can only do full on/full off with digital ports, but the timing feature would still be useful for the reasons you mentioned.  I'll just have to do a little work on the config tool side to enable it.

**Comment by gate001** [comment]
OK, I'll wait before redoing the connections on my chime board and my power board.

By the way, nice job on the this project and the expansion board project.

**Comment by mjrgh** [comment]
Here's a test build of the config tool with the flipper logic enabled for digital ports.  You should see a little "clock" icon on each digital port now.  Click it and select the time limit for the port. 

http://mjrnet.org/pinscape/downloads/PinscapeConfigTool-TimeLimiter1.zip

This uses the existing Flipper Logic feature in the firmware, so you don't need to update the firmware to use this.  The downside is that the Flipper Logic time limit is in 50ms increments, so the shortest time limit available is 50ms.  That might be too long for your chimes, so it might not help.  But I wanted to test this first before going in and messing with the firmware.

**Comment by gate001** [comment]
it works !!
I tried with the max and min pulse and we see the difference.
With 50ms, my chime has a better sound, but I think you're right, I'll need a shorter pulse.

**Comment by mjrgh** [comment]
Okay, here's something new for you to try...

http://mjrnet.org/pinscape/downloads/PinscapeConfigTool-ChimeLogic-1.zip

Important:  this contains both a Config Tool update **and** a firmware update.  The firmware update is in the ZIP file, named **Pinscape_Controller_ChimeLogic-1.bin**.  Extract that along with the other files and use the "Update" function in the config tool to install the new firmware.

This has a new feature, "Chime Logic".  Look for the chime icon that appears alongside the flipper icon in each output port row.  

Chime Logic is similar to Flipper Logic, but it lets you set finer gradations of time on the shorter end of the scale - 1ms, 2ms, 5ms, 10ms, 20ms, 40ms, 80ms, 100ms.   So I think this will help with your chimes if the 50ms minimum from Flipper Logic was too long.

Chime Logic also doesn't have the power level setting that Flipper Logic has.  Instead, it has a **minimum** time setting in addition to the maximum time.  The minimum time is for another use case - some people have observed devices that are too slow for the short ON/OFF pulse that DOF sometimes generates, and wanted a way to force a minimum pulse length.   For your case, it sounds like you won't need a minimum, so you can just set that to 0ms, but on the other hand maybe you'll find that you get optimal results with an exact pulse length and will want to set the minimum accordingly.

Let me know how this works for you.

**Comment by gate001** [comment]
I will try it tomorrow. Will I lose my current configuration? Can I save my configuration and load it once the new firmware is installed?

**Comment by mjrgh** [comment]
The firmware update process in the Config Tool keeps your current configuration.  Just use the Update icon (in the row of icons for the device - Settings, Backup, Update, ...).  You can also explicitly back up your settings via the Backup icon.  That'll save your settings to a file that you can later restore (via the same icon).

When the Update process prompts you to select the new firmware version to install, click "Browse for a file" and select the file that you extracted from the Zip.

**Comment by gate001** [comment]
it works!!!  You did your magic again.
My optimal setting is 10ms.

**Comment by mjrgh** [comment]
Great!  I'll post it as a regular release soon.

**Comment by gate001** [comment]
once the new release out, should I install it or it's the same that I already have.

**Comment by mjrgh** [comment]
> once the new release out, should I install it or it's the same that I already have.

I'll do a release that's exactly the same as this, so you can stick with your current setup.

**Comment by MikePinball** [comment]
Mike - just to check. I assume this will be an accumulated set of fixes including the one I raised for "Night Mode and Shift". This one is a good idea and good fix BTW.

**Comment by mjrgh** [comment]
>  I assume this will be an accumulated set of fixes including the one I raised for "Night Mode and Shift".

Right.

**Comment by mjrgh** [comment]
Just posted the new release.
