### ISSUE TITLE
Some Kl25Z pin assignments need to be read-only

### ISSUE THREAD

**Issue by MikePinball** [mjrgh/PinscapeConfigTool#12]
When using the Pinscape expansion boards (or Pinscape AIO), some pins need to be viewed at read-only and not changeable by the user. These pins are the ones listed as "Internal" in the overall pin listing. Examples are the pins used for the power board header.

`var gInternal = {
        "PTC10":  "TLC5940 XLAT",
        "PTC6":   "TLC5940 SIN",
        "PTC5":   "TLC5940 SCLK",
        "PTC7":   "TLC5940 BLANK",
        "PTA1":   "TLC5940 GSCLK",
        "PTC9":   "IR OUT",
        "PTA13":  "IR IN",
        "PTD2":   "PSU2 STATUS",
        "PTD3":   "TV RELAY",
        "PTE0":   "PSU2 LATCH"
    };`

**Comment by mjrgh** [comment]
I'm really not inclined to make anything read-only.  When you're in expansion board mode, all of the pin assignments are hidden anyway, so if you're showing them at all, you're asserting Power User status.  And having done that, you might actually want to change one of the supposedly immutable pins - e.g., you're using a customized version of the hardware.

**Comment by MikePinball** [comment]
Ok that's fine. I think your Power User scenario is fairly unlikely (except for you, me and maybe one other person).

However, perhaps you can add a comment next to the text to show this is "expert mode" e.g.
`Show KL25Z pin assignments <b>(Expert Mode)</b>`
