### ISSUE TITLE
NEW FEATURE REQUEST: Add 'JoystickMode' to PinscapeCmd

### ISSUE THREAD

**Issue by KrakenByteKraken** [mjrgh/PinscapeConfigTool#28]
The PinscapeConfigTool is amazing and I've used it for years and enjoy it too much because it works like a charm.

But, sometimes, I need to disable the joystik to let other games do their job without issues.

Then, I must to enter into the PinscapeConfigTool and reconfig my card saving this setting. Or, because all these steps are so long, I finished to create to config files, one with joystick enabled and other disabled. But it still is so slow and requires too many steps. If I could do...
 
I know that the Pinscape Command tool (PinscapeCmd) lets you send special command sequences to your Pinscape Controller unit(s), and is designed as a command-line utility to make it convenient to use in Windows command shell scripts (.CMD or .BAT files), to help you automate tasks. It's a very good improvement. So, please:

Could be possible to add an option to enable/disable joystick with PinscapeCmd? In example, something like this:

`JoystickMode=state : turn joystick mode ON or OFF (replace 'state' with ON or OFF according to which state you want to engage).`

It could be awesome. Anyway, congrats for your hard work and make this hobbie greater than ever.

Thanks and regards!

**Comment by mjrgh** [comment]
That's probably doable.  Is it sufficient to stop sending accelerometer input, or do you actually need the entire USB joystick interface to be removed (so that Windows doesn't see it as a joystick at all)? If it's only the accelerometer input that's the issue, that's fairly easy to implement, since it's just a matter of zeroing out the reports when the "disabled" mode is in effect.  If you need the entire joystick interface removed from Windows, that requires updating the stored configuration and rebooting the device, which makes it a bit more work to implement.  That's probably still possible, but I'd have to think about how it would interact with the config tool and backed-up state and so forth, since it requires updating the persistent configuration.  Zeroing out the accelerometer input, in contrast, could be implemented as a simple temporary run-time mode.

**Comment by KrakenByteKraken** [comment]
Zeroing out the accelerometer couldn't be enought because I believe that if Windows see it as joystick then begins the mess and its own device control checking for another game can't works propierly.

What I'm doing actually and it works fine, but its too complicated: I must have two config saved, one with joystick and other without it. And I must load one of them in the PinscapeConfigTool (yes, it reboots the device every time). So I think there are too steps, usually, in a lot of times when changing from pinball to another style of game.

I know that it could be slow, but instead, it could be automatic, so it still became will be a big improvement.

**Comment by mjrgh** [comment]
Removing the interface would be a bigger job, so I want to make sure I understand the use case, in case there's an easier way to accomplish the same thing.  Could you explain (a) the specific games that you're using that require this, and (b) the nature of the problem that occurs with the games?  Go into as much detail as possible so I can try to understand the technical cause of the problem(s).

**Comment by KrakenByteKraken** [comment]
The simptoms are that, sometimes, not all but it happens in a buch of games, some games don't like that the first joystick conected be the "Pinscape joystick" and then the game can't see the real gamepad until I have disabled the "Pinscape joystick": The game doesn't see any joystick and goes to keyboard control. It's impossible to play with gamepad.

After I disable 'Pinscape joystick', the game (or Windows, I really don't know who is, the game or Windows) works as is expected and it asigns the gamepad to joystick: The game sees the gamepad an goes to joystick control. Then it works fine and you can play with gamepad.

Some examples of games with this behavior (latest games which I'm remembering now) are:
- The Stanley Parable Ultra Deluxe.
- Portal.
- Subnautica.
- Garten of Banban 4.
- Enchanted Portals.

**Comment by KrakenByteKraken** [comment]
I was thinking about this and then I thought that other possible solution could be load a config file automatically through command line. In example, something like this:

`LoadConfig=C:\configs\configwithoutjoystick.psconfig`

What do you think about this alternative? Could it be easier?

THX in advance and regards.

**Comment by mjrgh** [comment]
That's what I had in mind, actually!
