### ISSUE TITLE
Question - Is there a way to retrieve the Night Mode State from Pinscape ?

### ISSUE THREAD

**Issue by Zappo-II** [mjrgh/PinscapeConfigTool#32]
Obviously there is a CLI to SET the Night Mode to ON or OFF (which is great) but is there also a way to GET the Night Mode State (isON, isOFF) ...???

I am planning to set those states automagically by cron (whatever that is called in windows) and optionally by user via shift keys, but I would also like to "Know" on the OS Level in what State the Cabinet is currently in...

THX and Cheers...

**Comment by mjrgh** [comment]
There's not a command-line option for that, but the information is in the HID reports, so it wouldn't be hard to add.  If you want to try mocking something up, you could add something like this to PinscapeCmd/Program.cs in that big ugly if-else tree that checks the command options:

```
  else if (al == "checknightmode")
  {
      byte[] rpt = device.ReadStatusReport();
      if (rpt == null)
         System.Console.Write("Unable to read device status\n");
      else
	 System.Console.Write("Night mode is " + (((rpt[1] & 0x02) != 0) ? "ON" : "OFF") + "\n");
  }
```

Of you could use whatever other means is more convenient for your purposes of passing the information back to the caller (such as setting the process exit code), assuming it's a .bat script or something like that.  If you want to write it as a standalone C# program, it would be even easier to just do the test and update all in the C# code.  You can use the PinscapeCmd project as an initial application skeleton for that - just delete the contents of Program.Main() and put your own code there instead.

**Comment by mjrgh** [comment]
At any rate, I can easily enough add the code above to the base code for the PinscapeCmd tool so that it'll be there in future builds.

**Comment by mjrgh** [comment]
Actually, since it's so small, I just added it - if you grab the latest commit from the github repo it'll be there.

**Comment by Zappo-II** [comment]
@mirgh THX, you're THE man ! Please be aware, that I really appreciate the lots of things you did for the Virtual Cab Building Community, for the last about 2 to 3 years it took me to build my Cab (and it's still not finished jet) I regularly consult your guide and stuff and always there's one detail more to find.
